from datetime import datetime
from datetime import date
from dateutil import relativedelta
import numpy as np

start = datetime(1990, 2, 1)
end = datetime(2005, 12, 31)

def get_portfolio_params():
    return {
        'expected_returns': {
            'AA': 0.03,
            'AAPL': 0.03,
            'AXP': 0.03,
            'BA': 0.03,
            'BAC': 0.03,
            'BP': 0.03,
            'CAT': 0.03,
            'CVX': 0.03,
            'DD': 0.03,
            'DIS': 0.03,
            'GE': 0.03,
            'HD': 0.03,
            'HPQ': 0.03,
            'IBM': 0.03,
            'INTC': 0.03,
            'JNJ': 0.03,
            'JPM': 0.03,
            'KO': 0.03,
            'MCD': 0.03,
            'MMM': 0.03,
            'MRK': 0.03,
            'MSFT': 0.03,
            'PFE': 0.03,
            'PG': 0.03,
            'T': 0.03,
            'TGT': 0.03,
            'UTX': 0.03,
            'VZ': 0.03,
            'WMT': 0.03,
            'XOM': 0.03
        },
        'holding_periods': {
            'AA': {'start': start, 'end': end},
            'AAPL': {'start': start, 'end': end},
            'AXP': {'start': start, 'end': end},
            'BA': {'start': start, 'end': end},
            'BAC': {'start': start, 'end': end},
            'BP': {'start': start, 'end': end},
            'CAT': {'start': start, 'end': end},
            'CVX': {'start': start, 'end': end},
            'DD': {'start': start, 'end': end},
            'DIS': {'start': start, 'end': end},
            'GE': {'start': start, 'end': end},
            'HD': {'start': start, 'end': end},
            'HPQ': {'start': start, 'end': end},
            'IBM': {'start': start, 'end': end},
            'INTC': {'start': start, 'end': end},
            'JNJ': {'start': start, 'end': end},
            'JPM': {'start': start, 'end': end},
            'KO': {'start': start, 'end': end},
            'MCD': {'start': start, 'end': end},
            'MMM': {'start': start, 'end': end},
            'MRK': {'start': start, 'end': end},
            'MSFT': {'start': start, 'end': end},
            'PFE': {'start': start, 'end': end},
            'PG': {'start': start, 'end': end},
            'T': {'start': start, 'end': end},
            'TGT': {'start': start, 'end': end},
            'UTX': {'start': start, 'end': end},
            'VZ': {'start': start, 'end': end},
            'WMT': {'start': start, 'end': end},
            'XOM': {'start': start, 'end': end}
        },
        'shares': {
            'AA': 55,
            'AAPL': 15,
            'AXP': 17,
            'BA': 56,
            'BAC': 110,
            'BP': 10,
            'CAT': 50,
            'CVX': 40,
            'DD': 20,
            'DIS': 15,
            'GE': 17,
            'HD': 66,
            'HPQ': 11,
            'IBM': 45,
            'INTC': 75,
            'JNJ': 60,
            'JPM': 37,
            'KO': 15,
            'MCD': 55,
            'MMM': 25,
            'MRK': 35,
            'MSFT': 27,
            'PFE': 65,
            'PG': 45,
            'T': 95,
            'TGT': 85,
            'UTX': 22,
            'VZ': 11,
            'WMT': 66,
            'XOM': 25
        },
        'constraints': {
            'min_position': 0.05,
            'max_position': 0.15,
            'target_gain': 0.03
        },
        'defaults': {
            'frequency': 'm',
            'start': start,
            'end': end
        }
    }